frase = 'curso em video python'
print(frase[9:21])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9::3])
print(len(frase))
print(frase.count('o'))
print(frase.find('deo'))
print(frase.capitalize())
print(frase.title())
print(frase.upper())
print(frase.lower())
print(frase.replace('o', 'um'))
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
print('-'.join(frase))

