a = input('Digite algo: ')
print('O tipo primtivo desse valor é {}'.format(type(a)))
print('Só tem espaço? ', a.isspace())
print('È um numero? ', a.isnumeric())
print('È alfabeto? ', a.isalpha())
print('È alfanumèrico? ', a.isalnum())
print('Está em maiuscula? ', a.isupper())
print('Está em minuscula? ', a.islower())
print('Está capitalizada? ', a.istitle())